### ISSUE TITLE
Commissioning does not take effect

### ISSUE THREAD

**Issue by wenber-yu** [jake142/laravel-service#2]
![image](https://user-images.githubusercontent.com/7148309/47776808-34456f80-dd2e-11e8-9b38-67ce7b8c1a05.png)
php version:7.2.11
laravel version:5.7

**Comment by jake142** [comment]
Im busy until next week. I’ll have look at it in the end of next week.

Enabling a service triggers:

composer require Services/V1/VideoToFrame

and adds the test folder to the phpunit.xml

Is it possible to run it manually?

Disabling a service triggers:

composer remove Services/V1/VideoToFrame

and removes the test folder from the phpunit.xml

**Comment by wenber-yu** [comment]
![image](https://user-images.githubusercontent.com/7148309/47979451-3b89c600-e0fe-11e8-97fe-b23adb809c86.png)
![image](https://user-images.githubusercontent.com/7148309/47979474-493f4b80-e0fe-11e8-8e8f-38b7f59c6a04.png)
composer.json Path:/Users/wenber/htdocs/oneself/me

**Comment by jake142** [comment]
Ok,

Has the following been added to the composer.json file:

"minimum-stability": "dev",
"prefer-stable": true

as stated in the release notes it should be added by the package. If not, could you please add it manually and try to run composer require again?

**Comment by jake142** [comment]
ok, in /Users/wenber/htdocs/oneself/me do you have the Services folder? Eg. Does this path exist:

/Users/wenber/htdocs/oneself/me/Services/V1/VideoToFrame

and in that folder, do your composer.json have:

{
  "name": "Services/V1/VideoToFrame",
  ...
  ..

**Comment by wenber-yu** [comment]
this path /Users/wenber/htdocs/oneself/me/Services/V1/VideoToFrame exist,
in that folder->composer.json have:
{
"name":"Services/V1/VideoToFrame",
}

**Comment by jake142** [comment]
Im not able to reproduce.

1. Are you using the latest version of laravel-service? (minor update from 0.1.6 -> 0.1.7 due to stubs bug)
2. Does composer.json contain:

    "minimum-stability": "dev",
    "prefer-stable": true

![image](https://user-images.githubusercontent.com/4847060/48216262-7b61df00-e384-11e8-8173-bdbf4179f13a.png)

Using:

php version PHP 7.2.3
laravel 5.7
