### ISSUE TITLE
Can I separate .env-variables and config?

### ISSUE THREAD

**Issue by marcus13371337** [jake142/laravel-service#3]
Hello,

Great package!

Can I somehow separate the configs and the .env variables for each service?

**Comment by jake142** [comment]
Added a global config file for laravel-service. Available in version 2.0.1

Usage:

1. Publish laravel-service config file with artisan vendor:publish
2. Access values by config('laravel-service.<version>.<service>.<config_file>.<value>');

The laravel-service config will be updated if you change/add/delete config files in your services.

An alternative is to publish each service config file using artisan vendor:publish. In that case you need to publish a new config file for every change.
